require File.expand_path('../cloud_encrypted_sync/master', __FILE__)
require File.expand_path('../cloud_encrypted_sync/cryptographer', __FILE__)
require File.expand_path('../cloud_encrypted_sync/adapter_template', __FILE__)
require File.expand_path('../cloud_encrypted_sync/dummy_adapter', __FILE__)
require File.expand_path('../cloud_encrypted_sync/s3_adapter', __FILE__)
require File.expand_path('../cloud_encrypted_sync/progress_meter', __FILE__)